# Generated by Django 6.0.2 on 2026-02-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena_api', '0002_codingtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CodingTask',
        ),
        migrations.DeleteModel(
            name='CoderProfile',
        ),
    ]
